spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:healthdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false

logging:
  level:
    org.springframework: ERROR
    ie.kihon.HealthCheck: ${LOGLEVEL:INFO}

settings:
  retry: ${RETRY:3}
  timeout: ${TIMEOUT:10}

